import type { UserRole } from '../auth/types';

type Res='TAB_HOME'|'TAB_WORK'|'TAB_MODULES'|'TAB_NOTIFICATIONS'|'TAB_MORE'|'MODULE_APPROVALS'|'MODULE_INVENTORY'|'MODULE_PROJECTS'|'MODULE_ASSETS'|'MODULE_FLEET'|'MODULE_OPERATIONS'|'MODULE_FINANCE'|'MODULE_EXPENSES'|'MODULE_EMPLOYEES'|'MODULE_PROCUREMENT'|'MODULE_HR'|'MODULE_SAFETY'|'MODULE_SAFETY_INSPECTIONS'|'MODULE_SAFETY_TRAININGS'|'MODULE_SAFETY_INCIDENTS'|'MODULE_REPORTS'|'MODULE_AI'|'MODULE_SETTINGS'|'MODULE_DOCUMENTS'|'WORK_APPROVALS'|'WORK_TASKS';

const NV:UserRole[]=['SUPER_ADMIN','CEO','CFO','DEPARTMENT_HEAD','ACCOUNTANT','PROCUREMENT_OFFICER','OPERATIONS_MANAGER','IT_MANAGER','HR_MANAGER','SAFETY_OFFICER','WAREHOUSE_MANAGER','EMPLOYEE'];
const ALL:UserRole[]=[...NV,'VENDOR'];

const R:Record<Res,UserRole[]>={
TAB_HOME:ALL,TAB_WORK:NV,TAB_MODULES:ALL,TAB_NOTIFICATIONS:ALL,TAB_MORE:ALL,
MODULE_APPROVALS:['SUPER_ADMIN','CEO','CFO','DEPARTMENT_HEAD','ACCOUNTANT','PROCUREMENT_OFFICER'],
MODULE_INVENTORY:['SUPER_ADMIN','CEO','WAREHOUSE_MANAGER','OPERATIONS_MANAGER','PROCUREMENT_OFFICER','EMPLOYEE'],
MODULE_PROJECTS:NV,
MODULE_ASSETS:['SUPER_ADMIN','CEO','OPERATIONS_MANAGER','WAREHOUSE_MANAGER','EMPLOYEE'],
MODULE_FLEET:['SUPER_ADMIN','CEO','CFO','OPERATIONS_MANAGER','WAREHOUSE_MANAGER','DEPARTMENT_HEAD','EMPLOYEE'],
MODULE_OPERATIONS:['SUPER_ADMIN','CEO','OPERATIONS_MANAGER','DEPARTMENT_HEAD'],
MODULE_FINANCE:['SUPER_ADMIN','CEO','CFO','ACCOUNTANT','PROCUREMENT_OFFICER'],
MODULE_PROCUREMENT:['SUPER_ADMIN','CEO','CFO','ACCOUNTANT','PROCUREMENT_OFFICER','OPERATIONS_MANAGER','WAREHOUSE_MANAGER','VENDOR'],
MODULE_HR:['SUPER_ADMIN','CEO','HR_MANAGER','DEPARTMENT_HEAD'],
MODULE_SAFETY:['SUPER_ADMIN','CEO','SAFETY_OFFICER','OPERATIONS_MANAGER'],
MODULE_EXPENSES:NV,
MODULE_EMPLOYEES:['SUPER_ADMIN','HR_MANAGER'],
MODULE_SAFETY_INSPECTIONS:['SUPER_ADMIN','SAFETY_OFFICER'],
MODULE_SAFETY_TRAININGS:['SUPER_ADMIN','SAFETY_OFFICER','HR_MANAGER'],
MODULE_SAFETY_INCIDENTS:['SUPER_ADMIN','SAFETY_OFFICER'],
MODULE_REPORTS:['SUPER_ADMIN','CEO','CFO','OPERATIONS_MANAGER','DEPARTMENT_HEAD'],
MODULE_AI:['SUPER_ADMIN','CEO','CFO','OPERATIONS_MANAGER','DEPARTMENT_HEAD','PROCUREMENT_OFFICER'],
MODULE_SETTINGS:['SUPER_ADMIN','CEO','IT_MANAGER'],
MODULE_DOCUMENTS:NV,
WORK_APPROVALS:['SUPER_ADMIN','CEO','CFO','DEPARTMENT_HEAD','ACCOUNTANT','PROCUREMENT_OFFICER'],
WORK_TASKS:NV,
};

export const canAccess=(role:UserRole,res:Res)=> (R[res]??[]).includes(role);
export const canAccessOptional=(role:UserRole|null|undefined,res:Res)=>!!role&&canAccess(role,res);
export type { Res as MobileResource };
