import type { UserRole } from '../auth/types';

type Res='TAB_HOME'|'TAB_WORK'|'TAB_MODULES'|'TAB_NOTIFICATIONS'|'TAB_MORE'|'MODULE_INVENTORY'|'MODULE_PROJECTS'|'MODULE_ASSETS'|'MODULE_EXPENSES'|'MODULE_EMPLOYEES'|'MODULE_SAFETY_INSPECTIONS'|'MODULE_SAFETY_TRAININGS'|'MODULE_DOCUMENTS'|'WORK_APPROVALS'|'WORK_TASKS';

const NV:UserRole[]=['SUPER_ADMIN','CEO','CFO','DEPARTMENT_HEAD','ACCOUNTANT','PROCUREMENT_OFFICER','OPERATIONS_MANAGER','IT_MANAGER','HR_MANAGER','SAFETY_OFFICER','WAREHOUSE_MANAGER','EMPLOYEE'];
const ALL:UserRole[]=[...NV,'VENDOR'];

const R:Record<Res,UserRole[]>={
TAB_HOME:ALL,TAB_WORK:NV,TAB_MODULES:NV,TAB_NOTIFICATIONS:ALL,TAB_MORE:ALL,
MODULE_INVENTORY:['SUPER_ADMIN','CEO','WAREHOUSE_MANAGER','OPERATIONS_MANAGER','PROCUREMENT_OFFICER','EMPLOYEE'],
MODULE_PROJECTS:NV,MODULE_ASSETS:['SUPER_ADMIN','CEO','OPERATIONS_MANAGER','WAREHOUSE_MANAGER','EMPLOYEE'],
MODULE_EXPENSES:NV,MODULE_EMPLOYEES:['SUPER_ADMIN','HR_MANAGER'],
MODULE_SAFETY_INSPECTIONS:['SUPER_ADMIN','SAFETY_OFFICER'],
MODULE_SAFETY_TRAININGS:['SUPER_ADMIN','SAFETY_OFFICER','HR_MANAGER'],
MODULE_DOCUMENTS:NV,
WORK_APPROVALS:['SUPER_ADMIN','CEO','CFO','DEPARTMENT_HEAD','ACCOUNTANT','PROCUREMENT_OFFICER'],
WORK_TASKS:NV,
};

export const canAccess=(role:UserRole,res:Res)=> (R[res]??[]).includes(role);
export const canAccessOptional=(role:UserRole|null|undefined,res:Res)=>!!role&&canAccess(role,res);
export type { Res as MobileResource };
