import {
  Home,
  ClipboardCheck,
  Package,
  HardHat,
  DollarSign,
  Brain,
  Users,
  Shield,
  BarChart3,
  Settings,
  Truck,
  TrendingUp,
  AlertTriangle,
  type LucideIcon,
} from 'lucide-react';
import { UserRole } from '@/types/auth';

export interface MenuItem {
  id: string;
  label: string;
  icon: LucideIcon;
  path?: string;
  roles: UserRole[];
  children?: MenuItem[];
  badge?: number;
}

export const menuItems: MenuItem[] = [
  {
    id: 'dashboard',
    label: 'Dashboard',
    icon: Home,
    path: '/dashboard',
    roles: [
      UserRole.SUPER_ADMIN,
      UserRole.CEO,
      UserRole.CFO,
      UserRole.DEPARTMENT_HEAD,
      UserRole.ACCOUNTANT,
      UserRole.PROCUREMENT_OFFICER,
      UserRole.OPERATIONS_MANAGER,
      UserRole.IT_MANAGER,
      UserRole.HR_MANAGER,
      UserRole.SAFETY_OFFICER,
      UserRole.WAREHOUSE_MANAGER,
      UserRole.EMPLOYEE,
    ],
  },
  {
    id: 'approvals',
    label: 'Approvals & Workflows',
    icon: ClipboardCheck,
    path: '/approvals',
    roles: [
      UserRole.SUPER_ADMIN,
      UserRole.CEO,
      UserRole.CFO,
      UserRole.DEPARTMENT_HEAD,
      UserRole.ACCOUNTANT,
      UserRole.PROCUREMENT_OFFICER,
    ],
    children: [
      {
        id: 'approvals-pending',
        label: 'My Pending Approvals',
        icon: ClipboardCheck,
        path: '/approvals/pending',
        roles: [UserRole.SUPER_ADMIN, UserRole.CEO, UserRole.CFO, UserRole.DEPARTMENT_HEAD],
      },
      {
        id: 'approvals-invoices',
        label: 'Invoice Approvals',
        icon: ClipboardCheck,
        path: '/approvals/invoices',
        roles: [UserRole.SUPER_ADMIN, UserRole.CEO, UserRole.CFO, UserRole.ACCOUNTANT],
      },
      {
        id: 'approvals-purchases',
        label: 'Purchase Requests',
        icon: ClipboardCheck,
        path: '/approvals/purchases',
        roles: [UserRole.SUPER_ADMIN, UserRole.CEO, UserRole.CFO, UserRole.PROCUREMENT_OFFICER],
      },
      {
        id: 'approvals-it',
        label: 'IT Requests',
        icon: ClipboardCheck,
        path: '/approvals/it-requests',
        roles: [UserRole.SUPER_ADMIN, UserRole.CEO, UserRole.IT_MANAGER],
      },
      {
        id: 'approvals-payments',
        label: 'Payment Requests',
        icon: ClipboardCheck,
        path: '/approvals/payments',
        roles: [UserRole.SUPER_ADMIN, UserRole.CEO, UserRole.CFO, UserRole.ACCOUNTANT],
      },
      {
        id: 'approvals-history',
        label: 'Approval History',
        icon: ClipboardCheck,
        path: '/approvals/history',
        roles: [UserRole.SUPER_ADMIN, UserRole.CEO, UserRole.CFO, UserRole.DEPARTMENT_HEAD],
      },
    ],
  },
  {
    id: 'inventory',
    label: 'Inventory',
    icon: Package,
    path: '/inventory',
    roles: [
      UserRole.SUPER_ADMIN,
      UserRole.CEO,
      UserRole.WAREHOUSE_MANAGER,
      UserRole.OPERATIONS_MANAGER,
      UserRole.PROCUREMENT_OFFICER,
      UserRole.EMPLOYEE,
    ],
    children: [
      {
        id: 'inventory-dashboard',
        label: 'Dashboard',
        icon: Package,
        path: '/inventory',
        roles: [UserRole.SUPER_ADMIN, UserRole.CEO, UserRole.WAREHOUSE_MANAGER, UserRole.OPERATIONS_MANAGER, UserRole.EMPLOYEE],
      },
      {
        id: 'inventory-items',
        label: 'Stock Items',
        icon: Package,
        path: '/inventory/items',
        roles: [UserRole.SUPER_ADMIN, UserRole.CEO, UserRole.WAREHOUSE_MANAGER, UserRole.OPERATIONS_MANAGER, UserRole.EMPLOYEE],
      },
      {
        id: 'inventory-movements',
        label: 'Stock Movements',
        icon: TrendingUp,
        path: '/inventory/movements',
        roles: [UserRole.SUPER_ADMIN, UserRole.CEO, UserRole.WAREHOUSE_MANAGER, UserRole.OPERATIONS_MANAGER],
      },
      {
        id: 'inventory-warehouses',
        label: 'Warehouses',
        icon: Package,
        path: '/inventory/warehouses',
        roles: [UserRole.SUPER_ADMIN, UserRole.CEO, UserRole.WAREHOUSE_MANAGER],
      },
      {
        id: 'inventory-reports',
        label: 'Reports & Analytics',
        icon: BarChart3,
        path: '/inventory/reports',
        roles: [UserRole.SUPER_ADMIN, UserRole.CEO, UserRole.WAREHOUSE_MANAGER, UserRole.OPERATIONS_MANAGER],
      },
      {
        id: 'inventory-expiry',
        label: 'Expiry Tracking',
        icon: AlertTriangle,
        path: '/inventory/reports/expiry',
        roles: [UserRole.SUPER_ADMIN, UserRole.CEO, UserRole.WAREHOUSE_MANAGER],
      },
    ],
  },
  {
    id: 'assets',
    label: 'Assets',
    icon: Truck,
    path: '/assets',
    roles: [
      UserRole.SUPER_ADMIN,
      UserRole.CEO,
      UserRole.OPERATIONS_MANAGER,
      UserRole.WAREHOUSE_MANAGER,
      UserRole.EMPLOYEE,
    ],
    children: [
      {
        id: 'assets-list',
        label: 'All Assets',
        icon: Truck,
        path: '/assets',
        roles: [UserRole.SUPER_ADMIN, UserRole.CEO, UserRole.OPERATIONS_MANAGER, UserRole.WAREHOUSE_MANAGER, UserRole.EMPLOYEE],
      },
      {
        id: 'assets-add',
        label: 'Add Asset',
        icon: Truck,
        path: '/assets/new',
        roles: [UserRole.SUPER_ADMIN, UserRole.CEO, UserRole.OPERATIONS_MANAGER],
      },
    ],
  },
  {
    id: 'operations',
    label: 'Operations',
    icon: HardHat,
    path: '/operations',
    roles: [UserRole.SUPER_ADMIN, UserRole.CEO, UserRole.OPERATIONS_MANAGER, UserRole.DEPARTMENT_HEAD],
    children: [
      {
        id: 'operations-projects',
        label: 'Projects',
        icon: HardHat,
        path: '/operations/projects',
        roles: [UserRole.SUPER_ADMIN, UserRole.CEO, UserRole.OPERATIONS_MANAGER],
      },
      {
        id: 'operations-production',
        label: 'Production Logs',
        icon: HardHat,
        path: '/operations/production',
        roles: [UserRole.SUPER_ADMIN, UserRole.OPERATIONS_MANAGER],
      },
      {
        id: 'operations-equipment',
        label: 'Equipment Usage',
        icon: HardHat,
        path: '/operations/equipment-usage',
        roles: [UserRole.SUPER_ADMIN, UserRole.OPERATIONS_MANAGER],
      },
      {
        id: 'operations-shifts',
        label: 'Shift Planning',
        icon: HardHat,
        path: '/operations/shifts',
        roles: [UserRole.SUPER_ADMIN, UserRole.OPERATIONS_MANAGER],
      },
      {
        id: 'operations-reports',
        label: 'Field Reports',
        icon: HardHat,
        path: '/operations/field-reports',
        roles: [UserRole.SUPER_ADMIN, UserRole.OPERATIONS_MANAGER, UserRole.EMPLOYEE],
      },
    ],
  },
  {
    id: 'finance',
    label: 'Finance & Procurement',
    icon: DollarSign,
    path: '/finance',
    roles: [UserRole.SUPER_ADMIN, UserRole.CEO, UserRole.CFO, UserRole.ACCOUNTANT, UserRole.PROCUREMENT_OFFICER],
    children: [
      {
        id: 'finance-invoices',
        label: 'Invoices',
        icon: DollarSign,
        path: '/finance/invoices',
        roles: [UserRole.SUPER_ADMIN, UserRole.CFO, UserRole.ACCOUNTANT],
      },
      {
        id: 'finance-po',
        label: 'Purchase Orders',
        icon: DollarSign,
        path: '/finance/purchase-orders',
        roles: [UserRole.SUPER_ADMIN, UserRole.CFO, UserRole.PROCUREMENT_OFFICER],
      },
      {
        id: 'finance-quotations',
        label: 'Quotations',
        icon: DollarSign,
        path: '/finance/quotations',
        roles: [UserRole.SUPER_ADMIN, UserRole.PROCUREMENT_OFFICER],
      },
      {
        id: 'finance-payments',
        label: 'Payments',
        icon: DollarSign,
        path: '/finance/payments',
        roles: [UserRole.SUPER_ADMIN, UserRole.CFO, UserRole.ACCOUNTANT],
      },
      {
        id: 'finance-expenses',
        label: 'Expense Reports',
        icon: DollarSign,
        path: '/finance/expenses',
        roles: [UserRole.SUPER_ADMIN, UserRole.CFO, UserRole.ACCOUNTANT],
      },
    ],
  },
  {
    id: 'ai',
    label: 'AI Insights',
    icon: Brain,
    path: '/ai',
    roles: [UserRole.SUPER_ADMIN, UserRole.CEO, UserRole.CFO, UserRole.OPERATIONS_MANAGER, UserRole.DEPARTMENT_HEAD],
    children: [
      {
        id: 'ai-summaries',
        label: 'Project Summaries',
        icon: Brain,
        path: '/ai/project-summaries',
        roles: [UserRole.SUPER_ADMIN, UserRole.CEO, UserRole.OPERATIONS_MANAGER],
      },
      {
        id: 'ai-procurement',
        label: 'Procurement Advisor',
        icon: Brain,
        path: '/ai/procurement-advisor',
        roles: [UserRole.SUPER_ADMIN, UserRole.CEO, UserRole.CFO],
      },
      {
        id: 'ai-maintenance',
        label: 'Maintenance Predictions',
        icon: Brain,
        path: '/ai/maintenance-predictions',
        roles: [UserRole.SUPER_ADMIN, UserRole.OPERATIONS_MANAGER],
      },
      {
        id: 'ai-knowledge',
        label: 'Knowledge Base (Q&A)',
        icon: Brain,
        path: '/ai/knowledge-base',
        roles: [UserRole.SUPER_ADMIN, UserRole.CEO, UserRole.DEPARTMENT_HEAD],
      },
      {
        id: 'ai-safety',
        label: 'Safety Assistant',
        icon: Brain,
        path: '/ai/safety-assistant',
        roles: [UserRole.SUPER_ADMIN, UserRole.SAFETY_OFFICER],
      },
      {
        id: 'ai-hr',
        label: 'HR Assistant',
        icon: Brain,
        path: '/ai/hr-assistant',
        roles: [UserRole.SUPER_ADMIN, UserRole.HR_MANAGER],
      },
    ],
  },
  {
    id: 'hr',
    label: 'HR & Personnel',
    icon: Users,
    path: '/hr',
    roles: [UserRole.SUPER_ADMIN, UserRole.CEO, UserRole.HR_MANAGER, UserRole.DEPARTMENT_HEAD],
    children: [
      {
        id: 'hr-employees',
        label: 'Employees',
        icon: Users,
        path: '/hr/employees',
        roles: [UserRole.SUPER_ADMIN, UserRole.HR_MANAGER],
      },
      {
        id: 'hr-attendance',
        label: 'Attendance',
        icon: Users,
        path: '/hr/attendance',
        roles: [UserRole.SUPER_ADMIN, UserRole.HR_MANAGER, UserRole.DEPARTMENT_HEAD],
      },
      {
        id: 'hr-recruitment',
        label: 'Recruitment',
        icon: Users,
        path: '/hr/recruitment',
        roles: [UserRole.SUPER_ADMIN, UserRole.HR_MANAGER],
      },
      {
        id: 'hr-performance',
        label: 'Performance',
        icon: Users,
        path: '/hr/performance',
        roles: [UserRole.SUPER_ADMIN, UserRole.HR_MANAGER, UserRole.DEPARTMENT_HEAD],
      },
    ],
  },
  {
    id: 'safety',
    label: 'Safety & Compliance',
    icon: Shield,
    path: '/safety',
    roles: [UserRole.SUPER_ADMIN, UserRole.CEO, UserRole.SAFETY_OFFICER, UserRole.OPERATIONS_MANAGER],
    children: [
      {
        id: 'safety-incidents',
        label: 'Incident Reports',
        icon: Shield,
        path: '/safety/incidents',
        roles: [UserRole.SUPER_ADMIN, UserRole.SAFETY_OFFICER],
      },
      {
        id: 'safety-inspections',
        label: 'Safety Inspections',
        icon: Shield,
        path: '/safety/inspections',
        roles: [UserRole.SUPER_ADMIN, UserRole.SAFETY_OFFICER],
      },
      {
        id: 'safety-compliance',
        label: 'Compliance Docs',
        icon: Shield,
        path: '/safety/compliance',
        roles: [UserRole.SUPER_ADMIN, UserRole.SAFETY_OFFICER],
      },
      {
        id: 'safety-training',
        label: 'Training Records',
        icon: Shield,
        path: '/safety/training',
        roles: [UserRole.SUPER_ADMIN, UserRole.SAFETY_OFFICER, UserRole.HR_MANAGER],
      },
    ],
  },
  {
    id: 'reports',
    label: 'Reports & Analytics',
    icon: BarChart3,
    path: '/reports',
    roles: [UserRole.SUPER_ADMIN, UserRole.CEO, UserRole.CFO, UserRole.OPERATIONS_MANAGER, UserRole.DEPARTMENT_HEAD],
    children: [
      {
        id: 'reports-operations',
        label: 'Operational Reports',
        icon: BarChart3,
        path: '/reports/operations',
        roles: [UserRole.SUPER_ADMIN, UserRole.CEO, UserRole.OPERATIONS_MANAGER],
      },
      {
        id: 'reports-financial',
        label: 'Financial Reports',
        icon: BarChart3,
        path: '/reports/financial',
        roles: [UserRole.SUPER_ADMIN, UserRole.CEO, UserRole.CFO],
      },
      {
        id: 'reports-inventory',
        label: 'Inventory Reports',
        icon: BarChart3,
        path: '/reports/inventory',
        roles: [UserRole.SUPER_ADMIN, UserRole.WAREHOUSE_MANAGER],
      },
      {
        id: 'reports-custom',
        label: 'Custom Reports',
        icon: BarChart3,
        path: '/reports/custom',
        roles: [UserRole.SUPER_ADMIN, UserRole.CEO],
      },
    ],
  },
  {
    id: 'settings',
    label: 'Settings',
    icon: Settings,
    path: '/settings',
    roles: [UserRole.SUPER_ADMIN, UserRole.CEO, UserRole.IT_MANAGER],
    children: [
      {
        id: 'settings-company',
        label: 'Company Profile',
        icon: Settings,
        path: '/settings/company',
        roles: [UserRole.SUPER_ADMIN, UserRole.CEO],
      },
      {
        id: 'settings-users',
        label: 'Users & Roles',
        icon: Settings,
        path: '/settings/users',
        roles: [UserRole.SUPER_ADMIN, UserRole.IT_MANAGER],
      },
      {
        id: 'settings-workflows',
        label: 'Approval Workflows',
        icon: Settings,
        path: '/settings/workflows',
        roles: [UserRole.SUPER_ADMIN, UserRole.CEO],
      },
      {
        id: 'settings-notifications',
        label: 'Notifications',
        icon: Settings,
        path: '/settings/notifications',
        roles: [UserRole.SUPER_ADMIN, UserRole.IT_MANAGER],
      },
      {
        id: 'settings-system',
        label: 'System Settings',
        icon: Settings,
        path: '/settings/system',
        roles: [UserRole.SUPER_ADMIN, UserRole.IT_MANAGER],
      },
    ],
  },
];
