import {
  Home,
  ClipboardCheck,
  Package,
  HardHat,
  DollarSign,
  Brain,
  Search,
  Users,
  Shield,
  BarChart3,
  Settings,
  Truck,
  TrendingUp,
  AlertTriangle,
  FileText,
  Upload,
  Calendar,
  DatabaseBackup,
  FileSpreadsheet,
  type LucideIcon,
} from 'lucide-react';
import { UserRole } from '@/types/auth';

export interface MenuItem {
  id: string;
  label: string;
  icon: LucideIcon;
  path?: string;
  roles: UserRole[];
  children?: MenuItem[];
  badge?: number;
}

export const menuItems: MenuItem[] = [
  {
    id: 'dashboard',
    label: 'Dashboard',
    icon: Home,
    path: '/dashboard',
    roles: [
      UserRole.SUPER_ADMIN,
      UserRole.CEO,
      UserRole.CFO,
      UserRole.DEPARTMENT_HEAD,
      UserRole.ACCOUNTANT,
      UserRole.PROCUREMENT_OFFICER,
      UserRole.OPERATIONS_MANAGER,
      UserRole.IT_MANAGER,
      UserRole.HR_MANAGER,
      UserRole.SAFETY_OFFICER,
      UserRole.WAREHOUSE_MANAGER,
      UserRole.EMPLOYEE,
    ],
  },
  {
    id: 'approvals',
    label: 'Approvals & Workflows',
    icon: ClipboardCheck,
    path: '/approvals',
    roles: [
      UserRole.SUPER_ADMIN,
      UserRole.CEO,
      UserRole.CFO,
      UserRole.DEPARTMENT_HEAD,
      UserRole.ACCOUNTANT,
      UserRole.PROCUREMENT_OFFICER,
    ],
    children: [
      {
        id: 'approvals-pending',
        label: 'My Pending Approvals',
        icon: ClipboardCheck,
        path: '/approvals/pending',
        roles: [UserRole.SUPER_ADMIN, UserRole.CEO, UserRole.CFO, UserRole.DEPARTMENT_HEAD],
      },
      {
        id: 'approvals-invoices',
        label: 'Invoice Approvals',
        icon: ClipboardCheck,
        path: '/approvals/invoices',
        roles: [UserRole.SUPER_ADMIN, UserRole.CEO, UserRole.CFO, UserRole.ACCOUNTANT],
      },
      {
        id: 'approvals-purchases',
        label: 'Purchase Requests',
        icon: ClipboardCheck,
        path: '/approvals/purchases',
        roles: [UserRole.SUPER_ADMIN, UserRole.CEO, UserRole.CFO, UserRole.PROCUREMENT_OFFICER],
      },
      {
        id: 'approvals-it',
        label: 'IT Requests',
        icon: ClipboardCheck,
        path: '/approvals/it-requests',
        roles: [UserRole.SUPER_ADMIN, UserRole.CEO, UserRole.IT_MANAGER],
      },
      {
        id: 'approvals-payments',
        label: 'Payment Requests',
        icon: ClipboardCheck,
        path: '/approvals/payment-requests',
        roles: [UserRole.SUPER_ADMIN, UserRole.CEO, UserRole.CFO, UserRole.ACCOUNTANT],
      },
      {
        id: 'approvals-history',
        label: 'Approval History',
        icon: ClipboardCheck,
        path: '/approvals/history',
        roles: [UserRole.SUPER_ADMIN, UserRole.CEO, UserRole.CFO, UserRole.DEPARTMENT_HEAD],
      },
    ],
  },
  {
    id: 'inventory',
    label: 'Inventory',
    icon: Package,
    path: '/inventory',
    roles: [
      UserRole.SUPER_ADMIN,
      UserRole.CEO,
      UserRole.WAREHOUSE_MANAGER,
      UserRole.OPERATIONS_MANAGER,
      UserRole.PROCUREMENT_OFFICER,
      UserRole.EMPLOYEE,
    ],
    children: [
      {
        id: 'inventory-dashboard',
        label: 'Dashboard',
        icon: Package,
        path: '/inventory',
        roles: [UserRole.SUPER_ADMIN, UserRole.CEO, UserRole.WAREHOUSE_MANAGER, UserRole.OPERATIONS_MANAGER, UserRole.EMPLOYEE],
      },
      {
        id: 'inventory-items',
        label: 'Stock Items',
        icon: Package,
        path: '/inventory/items',
        roles: [UserRole.SUPER_ADMIN, UserRole.CEO, UserRole.WAREHOUSE_MANAGER, UserRole.OPERATIONS_MANAGER, UserRole.EMPLOYEE],
      },
      {
        id: 'inventory-movements',
        label: 'Stock Movements',
        icon: TrendingUp,
        path: '/inventory/movements',
        roles: [UserRole.SUPER_ADMIN, UserRole.CEO, UserRole.WAREHOUSE_MANAGER, UserRole.OPERATIONS_MANAGER],
      },
      {
        id: 'inventory-warehouses',
        label: 'Warehouses',
        icon: Package,
        path: '/inventory/warehouses',
        roles: [UserRole.SUPER_ADMIN, UserRole.CEO, UserRole.WAREHOUSE_MANAGER],
      },
      {
        id: 'inventory-reports',
        label: 'Reports & Analytics',
        icon: BarChart3,
        path: '/inventory/reports',
        roles: [UserRole.SUPER_ADMIN, UserRole.CEO, UserRole.WAREHOUSE_MANAGER, UserRole.OPERATIONS_MANAGER],
      },
      {
        id: 'inventory-expiry',
        label: 'Expiry Tracking',
        icon: AlertTriangle,
        path: '/inventory/reports/expiry',
        roles: [UserRole.SUPER_ADMIN, UserRole.CEO, UserRole.WAREHOUSE_MANAGER],
      },
    ],
  },
  {
    id: 'assets',
    label: 'Assets',
    icon: Truck,
    path: '/assets',
    roles: [
      UserRole.SUPER_ADMIN,
      UserRole.CEO,
      UserRole.OPERATIONS_MANAGER,
      UserRole.WAREHOUSE_MANAGER,
      UserRole.EMPLOYEE,
    ],
    children: [
      {
        id: 'assets-list',
        label: 'All Assets',
        icon: Truck,
        path: '/assets',
        roles: [UserRole.SUPER_ADMIN, UserRole.CEO, UserRole.OPERATIONS_MANAGER, UserRole.WAREHOUSE_MANAGER, UserRole.EMPLOYEE],
      },
      {
        id: 'assets-add',
        label: 'Add Asset',
        icon: Truck,
        path: '/assets/new',
        roles: [UserRole.SUPER_ADMIN, UserRole.CEO, UserRole.OPERATIONS_MANAGER],
      },
    ],
  },
  {
    id: 'operations',
    label: 'Operations',
    icon: HardHat,
    path: '/operations',
    roles: [UserRole.SUPER_ADMIN, UserRole.CEO, UserRole.OPERATIONS_MANAGER, UserRole.DEPARTMENT_HEAD],
    children: [
      {
        id: 'operations-projects',
        label: 'Projects',
        icon: HardHat,
        path: '/projects',
        roles: [UserRole.SUPER_ADMIN, UserRole.CEO, UserRole.OPERATIONS_MANAGER],
      },
      {
        id: 'operations-production',
        label: 'Production Logs',
        icon: HardHat,
        path: '/operations/production',
        roles: [UserRole.SUPER_ADMIN, UserRole.OPERATIONS_MANAGER],
      },
      {
        id: 'operations-equipment',
        label: 'Equipment Usage',
        icon: HardHat,
        path: '/operations/equipment-usage',
        roles: [UserRole.SUPER_ADMIN, UserRole.OPERATIONS_MANAGER],
      },
      {
        id: 'operations-shifts',
        label: 'Shift Planning',
        icon: HardHat,
        path: '/operations/shifts',
        roles: [UserRole.SUPER_ADMIN, UserRole.OPERATIONS_MANAGER],
      },
      {
        id: 'operations-reports',
        label: 'Field Reports',
        icon: HardHat,
        path: '/operations/field-reports',
        roles: [UserRole.SUPER_ADMIN, UserRole.OPERATIONS_MANAGER, UserRole.EMPLOYEE],
      },
    ],
  },
  {
    id: 'finance',
    label: 'Finance & Procurement',
    icon: DollarSign,
    path: '/finance',
    roles: [UserRole.SUPER_ADMIN, UserRole.CEO, UserRole.CFO, UserRole.ACCOUNTANT, UserRole.PROCUREMENT_OFFICER],
    children: [
      {
        id: 'finance-dashboard',
        label: 'Finance Dashboard',
        icon: DollarSign,
        path: '/finance',
        roles: [UserRole.SUPER_ADMIN, UserRole.CEO, UserRole.CFO, UserRole.ACCOUNTANT],
      },
      {
        id: 'finance-payments',
        label: 'Payments',
        icon: DollarSign,
        path: '/finance/payments',
        roles: [UserRole.SUPER_ADMIN, UserRole.CFO, UserRole.ACCOUNTANT],
      },
      {
        id: 'finance-expenses',
        label: 'Expenses',
        icon: DollarSign,
        path: '/finance/expenses',
        roles: [UserRole.SUPER_ADMIN, UserRole.CFO, UserRole.ACCOUNTANT, UserRole.EMPLOYEE],
      },
      {
        id: 'finance-budgets',
        label: 'Budgets',
        icon: DollarSign,
        path: '/finance/budgets',
        roles: [UserRole.SUPER_ADMIN, UserRole.CEO, UserRole.CFO],
      },
      {
        id: 'finance-suppliers',
        label: 'Suppliers',
        icon: DollarSign,
        path: '/finance/suppliers',
        roles: [UserRole.SUPER_ADMIN, UserRole.CFO, UserRole.PROCUREMENT_OFFICER],
      },
      {
        id: 'procurement-requisitions',
        label: 'Requisitions',
        icon: ClipboardCheck,
        path: '/procurement/requisitions',
        roles: [UserRole.SUPER_ADMIN, UserRole.CEO, UserRole.CFO, UserRole.PROCUREMENT_OFFICER, UserRole.DEPARTMENT_HEAD, UserRole.OPERATIONS_MANAGER, UserRole.WAREHOUSE_MANAGER, UserRole.EMPLOYEE],
      },
    ],
  },
  {
    id: 'documents',
    label: 'Documents & Files',
    icon: FileText,
    path: '/documents',
    roles: [
      UserRole.SUPER_ADMIN,
      UserRole.CEO,
      UserRole.CFO,
      UserRole.DEPARTMENT_HEAD,
      UserRole.ACCOUNTANT,
      UserRole.PROCUREMENT_OFFICER,
      UserRole.OPERATIONS_MANAGER,
      UserRole.IT_MANAGER,
      UserRole.HR_MANAGER,
      UserRole.SAFETY_OFFICER,
      UserRole.WAREHOUSE_MANAGER,
      UserRole.EMPLOYEE,
    ],
    children: [
      {
        id: 'documents-all',
        label: 'All Documents',
        icon: FileText,
        path: '/documents',
        roles: [UserRole.SUPER_ADMIN, UserRole.CEO, UserRole.CFO, UserRole.DEPARTMENT_HEAD, UserRole.ACCOUNTANT, UserRole.PROCUREMENT_OFFICER, UserRole.OPERATIONS_MANAGER, UserRole.IT_MANAGER, UserRole.HR_MANAGER, UserRole.SAFETY_OFFICER, UserRole.WAREHOUSE_MANAGER, UserRole.EMPLOYEE],
      },
      {
        id: 'documents-smart-search',
        label: 'Smart Search',
        icon: Search,
        path: '/documents/smart-search',
        roles: [UserRole.SUPER_ADMIN, UserRole.CEO, UserRole.CFO, UserRole.DEPARTMENT_HEAD, UserRole.ACCOUNTANT, UserRole.PROCUREMENT_OFFICER, UserRole.OPERATIONS_MANAGER, UserRole.IT_MANAGER, UserRole.HR_MANAGER, UserRole.SAFETY_OFFICER, UserRole.WAREHOUSE_MANAGER, UserRole.EMPLOYEE],
      },
      {
        id: 'documents-shared',
        label: 'Shared Documents',
        icon: FileText,
        path: '/documents/shared',
        roles: [UserRole.SUPER_ADMIN, UserRole.CEO, UserRole.CFO, UserRole.DEPARTMENT_HEAD, UserRole.ACCOUNTANT, UserRole.PROCUREMENT_OFFICER, UserRole.OPERATIONS_MANAGER, UserRole.IT_MANAGER, UserRole.HR_MANAGER, UserRole.SAFETY_OFFICER, UserRole.WAREHOUSE_MANAGER, UserRole.EMPLOYEE],
      },
      {
        id: 'documents-tools',
        label: 'PDF Tools',
        icon: FileText,
        path: '/documents/tools',
        roles: [UserRole.SUPER_ADMIN, UserRole.CEO, UserRole.CFO, UserRole.DEPARTMENT_HEAD, UserRole.ACCOUNTANT, UserRole.PROCUREMENT_OFFICER, UserRole.OPERATIONS_MANAGER, UserRole.IT_MANAGER, UserRole.HR_MANAGER, UserRole.SAFETY_OFFICER, UserRole.WAREHOUSE_MANAGER, UserRole.EMPLOYEE],
      },
      {
        id: 'documents-my',
        label: 'My Uploads',
        icon: Upload,
        path: '/documents/my-uploads',
        roles: [UserRole.SUPER_ADMIN, UserRole.CEO, UserRole.CFO, UserRole.DEPARTMENT_HEAD, UserRole.ACCOUNTANT, UserRole.PROCUREMENT_OFFICER, UserRole.OPERATIONS_MANAGER, UserRole.IT_MANAGER, UserRole.HR_MANAGER, UserRole.SAFETY_OFFICER, UserRole.WAREHOUSE_MANAGER, UserRole.EMPLOYEE],
      },
      {
        id: 'documents-finance',
        label: 'Finance Documents',
        icon: DollarSign,
        path: '/documents?category=INVOICE',
        roles: [UserRole.SUPER_ADMIN, UserRole.CEO, UserRole.CFO, UserRole.ACCOUNTANT],
      },
      {
        id: 'documents-safety',
        label: 'Safety Documents',
        icon: Shield,
        path: '/documents?category=SAFETY',
        roles: [UserRole.SUPER_ADMIN, UserRole.CEO, UserRole.SAFETY_OFFICER, UserRole.OPERATIONS_MANAGER],
      },
      {
        id: 'documents-hr',
        label: 'HR Documents',
        icon: Users,
        path: '/documents?category=HR',
        roles: [UserRole.SUPER_ADMIN, UserRole.CEO, UserRole.HR_MANAGER],
      },
      {
        id: 'documents-projects',
        label: 'Project Documents',
        icon: HardHat,
        path: '/documents?category=PROJECT',
        roles: [UserRole.SUPER_ADMIN, UserRole.CEO, UserRole.OPERATIONS_MANAGER, UserRole.DEPARTMENT_HEAD],
      },
    ],
  },
  {
    id: 'ai',
    label: 'AI Intelligence',
    icon: Brain,
    path: '/ai',
    roles: [UserRole.SUPER_ADMIN, UserRole.CEO, UserRole.CFO, UserRole.OPERATIONS_MANAGER, UserRole.DEPARTMENT_HEAD, UserRole.PROCUREMENT_OFFICER],
    children: [
      {
        id: 'ai-dashboard',
        label: 'AI Dashboard',
        icon: Brain,
        path: '/ai',
        roles: [UserRole.SUPER_ADMIN, UserRole.CEO, UserRole.CFO, UserRole.OPERATIONS_MANAGER, UserRole.DEPARTMENT_HEAD],
      },
      {
        id: 'ai-summaries',
        label: 'Project Summaries',
        icon: Brain,
        path: '/ai/project-summaries',
        roles: [UserRole.SUPER_ADMIN, UserRole.CEO, UserRole.OPERATIONS_MANAGER, UserRole.DEPARTMENT_HEAD],
      },
      {
        id: 'ai-procurement',
        label: 'Procurement Advisor',
        icon: Brain,
        path: '/ai/procurement-advisor',
        roles: [UserRole.SUPER_ADMIN, UserRole.CEO, UserRole.CFO, UserRole.PROCUREMENT_OFFICER],
      },
      {
        id: 'ai-maintenance',
        label: 'Maintenance Predictor',
        icon: Brain,
        path: '/ai/maintenance-predictor',
        roles: [UserRole.SUPER_ADMIN, UserRole.CEO, UserRole.OPERATIONS_MANAGER],
      },
      {
        id: 'ai-knowledge',
        label: 'Knowledge Engine',
        icon: Brain,
        path: '/ai/knowledge-engine',
        roles: [UserRole.SUPER_ADMIN, UserRole.CEO, UserRole.OPERATIONS_MANAGER, UserRole.SAFETY_OFFICER, UserRole.HR_MANAGER],
      },
      {
        id: 'ai-safety',
        label: 'Safety Assistant',
        icon: Brain,
        path: '/ai/safety-assistant',
        roles: [UserRole.SUPER_ADMIN, UserRole.CEO, UserRole.OPERATIONS_MANAGER, UserRole.SAFETY_OFFICER],
      },
    ],
  },
  {
    id: 'hr',
    label: 'HR & Personnel',
    icon: Users,
    path: '/hr',
    roles: [UserRole.SUPER_ADMIN, UserRole.CEO, UserRole.HR_MANAGER, UserRole.DEPARTMENT_HEAD],
    children: [
      {
        id: 'hr-employees',
        label: 'Employees',
        icon: Users,
        path: '/hr/employees',
        roles: [UserRole.SUPER_ADMIN, UserRole.HR_MANAGER],
      },
      {
        id: 'hr-attendance',
        label: 'Attendance',
        icon: Users,
        path: '/hr/attendance',
        roles: [UserRole.SUPER_ADMIN, UserRole.HR_MANAGER, UserRole.DEPARTMENT_HEAD],
      },
      {
        id: 'hr-leave-requests',
        label: 'Leave Requests',
        icon: Users,
        path: '/hr/leave-requests',
        roles: [UserRole.SUPER_ADMIN, UserRole.HR_MANAGER, UserRole.DEPARTMENT_HEAD],
      },
      {
        id: 'hr-recruitment',
        label: 'Recruitment',
        icon: Users,
        path: '/hr/recruitment',
        roles: [UserRole.SUPER_ADMIN, UserRole.HR_MANAGER],
      },
      {
        id: 'hr-performance',
        label: 'Performance',
        icon: Users,
        path: '/hr/performance',
        roles: [UserRole.SUPER_ADMIN, UserRole.HR_MANAGER, UserRole.DEPARTMENT_HEAD],
      },
    ],
  },
  {
    id: 'safety',
    label: 'Safety & Compliance',
    icon: Shield,
    path: '/safety',
    roles: [UserRole.SUPER_ADMIN, UserRole.CEO, UserRole.SAFETY_OFFICER, UserRole.OPERATIONS_MANAGER],
    children: [
      {
        id: 'safety-incidents',
        label: 'Incident Reports',
        icon: Shield,
        path: '/safety/incidents',
        roles: [UserRole.SUPER_ADMIN, UserRole.SAFETY_OFFICER],
      },
      {
        id: 'safety-inspections',
        label: 'Safety Inspections',
        icon: Shield,
        path: '/safety/inspections',
        roles: [UserRole.SUPER_ADMIN, UserRole.SAFETY_OFFICER],
      },
      {
        id: 'safety-compliance',
        label: 'Compliance Docs',
        icon: Shield,
        path: '/safety/compliance',
        roles: [UserRole.SUPER_ADMIN, UserRole.SAFETY_OFFICER],
      },
      {
        id: 'safety-training',
        label: 'Training Records',
        icon: Shield,
        path: '/safety/trainings',
        roles: [UserRole.SUPER_ADMIN, UserRole.SAFETY_OFFICER, UserRole.HR_MANAGER],
      },
      {
        id: 'safety-certifications',
        label: 'Certifications',
        icon: Shield,
        path: '/safety/certifications',
        roles: [UserRole.SUPER_ADMIN, UserRole.SAFETY_OFFICER, UserRole.HR_MANAGER],
      },
      {
        id: 'safety-drills',
        label: 'Safety Drills',
        icon: Shield,
        path: '/safety/drills',
        roles: [UserRole.SUPER_ADMIN, UserRole.SAFETY_OFFICER, UserRole.OPERATIONS_MANAGER],
      },
    ],
  },
  {
    id: 'reports',
    label: 'Reports & Analytics',
    icon: BarChart3,
    path: '/reports',
    roles: [UserRole.SUPER_ADMIN, UserRole.CEO, UserRole.CFO, UserRole.OPERATIONS_MANAGER, UserRole.DEPARTMENT_HEAD],
    children: [
      {
        id: 'reports-financial',
        label: 'Financial Reports',
        icon: BarChart3,
        path: '/reports/financial',
        roles: [UserRole.SUPER_ADMIN, UserRole.CEO, UserRole.CFO],
      },
      {
        id: 'reports-operational',
        label: 'Operational Reports',
        icon: BarChart3,
        path: '/reports/operational',
        roles: [UserRole.SUPER_ADMIN, UserRole.CEO, UserRole.OPERATIONS_MANAGER],
      },
      {
        id: 'reports-hr',
        label: 'HR Reports',
        icon: BarChart3,
        path: '/reports/hr',
        roles: [UserRole.SUPER_ADMIN, UserRole.CEO, UserRole.HR_MANAGER],
      },
      {
        id: 'reports-safety',
        label: 'Safety Reports',
        icon: BarChart3,
        path: '/reports/safety',
        roles: [UserRole.SUPER_ADMIN, UserRole.CEO, UserRole.SAFETY_OFFICER],
      },
    ],
  },
  {
    id: 'settings',
    label: 'Settings',
    icon: Settings,
    path: '/settings',
    roles: [UserRole.SUPER_ADMIN, UserRole.CEO, UserRole.IT_MANAGER],
    children: [
      {
        id: 'settings-profile',
        label: 'My Profile',
        icon: Settings,
        path: '/settings/profile',
        roles: [UserRole.SUPER_ADMIN, UserRole.CEO, UserRole.CFO, UserRole.DEPARTMENT_HEAD, UserRole.ACCOUNTANT, UserRole.PROCUREMENT_OFFICER, UserRole.OPERATIONS_MANAGER, UserRole.IT_MANAGER, UserRole.HR_MANAGER, UserRole.SAFETY_OFFICER, UserRole.WAREHOUSE_MANAGER, UserRole.EMPLOYEE],
      },
      {
        id: 'settings-csv',
        label: 'CSV Import/Export',
        icon: Settings,
        path: '/settings/csv',
        roles: [UserRole.SUPER_ADMIN, UserRole.IT_MANAGER],
      },
      {
        id: 'settings-import-export',
        label: 'Import/Export',
        icon: FileSpreadsheet,
        path: '/settings/import-export',
        roles: [UserRole.SUPER_ADMIN, UserRole.CEO, UserRole.IT_MANAGER],
      },
      {
        id: 'settings-data-migration',
        label: 'Data Migration',
        icon: DatabaseBackup,
        path: '/settings/data-migration',
        roles: [UserRole.SUPER_ADMIN, UserRole.IT_MANAGER],
      },
      {
        id: 'settings-scheduled-exports',
        label: 'Scheduled Exports',
        icon: Calendar,
        path: '/settings/scheduled-exports',
        roles: [UserRole.SUPER_ADMIN, UserRole.CEO, UserRole.CFO, UserRole.IT_MANAGER],
      },
      {
        id: 'settings-users',
        label: 'User Management',
        icon: Settings,
        path: '/settings/users',
        roles: [UserRole.SUPER_ADMIN, UserRole.IT_MANAGER],
      },
      {
        id: 'settings-system',
        label: 'System Configuration',
        icon: Settings,
        path: '/settings/system',
        roles: [UserRole.SUPER_ADMIN, UserRole.IT_MANAGER],
      },
      {
        id: 'settings-notifications',
        label: 'Notifications',
        icon: Settings,
        path: '/settings/notifications',
        roles: [UserRole.SUPER_ADMIN, UserRole.IT_MANAGER],
      },
      {
        id: 'settings-audit',
        label: 'Audit Logs',
        icon: Settings,
        path: '/settings/audit-logs',
        roles: [UserRole.SUPER_ADMIN, UserRole.CEO],
      },
      {
        id: 'settings-ai',
        label: 'AI & Integrations',
        icon: Brain,
        path: '/settings/ai',
        roles: [UserRole.SUPER_ADMIN, UserRole.IT_MANAGER],
      },
      {
        id: 'settings-roles',
        label: 'Roles & Permissions',
        icon: Shield,
        path: '/settings/roles',
        roles: [UserRole.SUPER_ADMIN, UserRole.CEO, UserRole.IT_MANAGER],
      },
    ],
  },
];
